const seed = async function (knex) {
  await knex('fake_stocks').del();
  await knex('fake_stocks').insert([
    {
      symbol: 'AAPL',
      company_name: 'Apple Inc.',
      sector: 'Technology',
      price: 150,
      volume: 100000,
      last_updated: new Date().toISOString(),
      day_change: 0.5,
      '52_Week_High': 200,
      '52_Week_Low': 100,
      EPS: 3.15,
      P_E_Ratio: 30,
      Dividend_Yield: 0.6,
      Market_Cap: 2000000000,
      Beta: 1.2,
    },
    {
      symbol: 'MSFT',
      company_name: 'Microsoft Corporation',
      sector: 'Technology',
      price: 300,
      volume: 80000,
      last_updated: new Date().toISOString(),
      day_change: -1.2,
      '52_Week_High': 350,
      '52_Week_Low': 250,
      EPS: 5.75,
      P_E_Ratio: 33,
      Dividend_Yield: 0.8,
      Market_Cap: 2000000000,
      Beta: 1.1,
    },
    {
      symbol: 'GOOGL',
      company_name: 'Alphabet Inc.',
      sector: 'Technology',
      price: 2800,
      volume: 50000,
      last_updated: new Date().toISOString(),
      day_change: 1.8,
      '52_Week_High': 3000,
      '52_Week_Low': 2400,
      EPS: 50.25,
      P_E_Ratio: 30.5,
      Dividend_Yield: 0.5,
      Market_Cap: 1800000000,
      Beta: 1,
    },
    {
      symbol: 'BA',
      company_name: 'Boeing Co.',
      sector: 'Industrials',
      price: 243.78,
      volume: 95123,
      last_updated: new Date().toISOString(),
      day_change: -0.43,
      '52_Week_High': 278.57,
      '52_Week_Low': 174.35,
      EPS: 5.36,
      P_E_Ratio: 24.7,
      Dividend_Yield: 1.2,
      Market_Cap: 145200000,
      Beta: 1.3,
    },
    {
      symbol: 'AMZN',
      company_name: 'Amazon.com Inc.',
      sector: 'Consumer Discretionary',
      price: 3300,
      volume: 41000,
      last_updated: new Date().toISOString(),
      day_change: -12,
      '52_Week_High': 3550,
      '52_Week_Low': 2900,
      EPS: 52.3,
      P_E_Ratio: 63.1,
      Dividend_Yield: 0,
      Market_Cap: 1650000000,
      Beta: 1.1,
    },
    {
      symbol: 'NFLX',
      company_name: 'Netflix, Inc.',
      sector: 'Communication Services',
      price: 550,
      volume: 34000,
      last_updated: new Date().toISOString(),
      day_change: 2.5,
      '52_Week_High': 600,
      '52_Week_Low': 480,
      EPS: 4.13,
      P_E_Ratio: 40,
      Dividend_Yield: 0,
      Market_Cap: 240000000,
      Beta: 0.9,
    },
    {
      symbol: 'TSLA',
      company_name: 'Tesla, Inc.',
      sector: 'Consumer Discretionary',
      price: 700,
      volume: 56000,
      last_updated: new Date().toISOString(),
      day_change: 4.7,
      '52_Week_High': 900,
      '52_Week_Low': 500,
      EPS: 1.24,
      P_E_Ratio: 80,
      Dividend_Yield: 0,
      Market_Cap: 800000000,
      Beta: 2,
    },
    {
      symbol: 'JPM',
      company_name: 'JPMorgan Chase & Co.',
      sector: 'Financials',
      price: 150,
      volume: 32000,
      last_updated: new Date().toISOString(),
      day_change: 0.4,
      '52_Week_High': 170,
      '52_Week_Low': 130,
      EPS: 8.95,
      P_E_Ratio: 12,
      Dividend_Yield: 1.6,
      Market_Cap: 470000000,
      Beta: 1.2,
    },
    {
      symbol: 'NVDA',
      company_name: 'NVIDIA Corporation',
      sector: 'Technology',
      price: 220,
      volume: 29000,
      last_updated: new Date().toISOString(),
      day_change: 0.8,
      '52_Week_High': 250,
      '52_Week_Low': 180,
      EPS: 6.45,
      P_E_Ratio: 28,
      Dividend_Yield: 0.3,
      Market_Cap: 550000000,
      Beta: 1.3,
    },
    {
      symbol: 'BAC',
      company_name: 'Bank of America Corp',
      sector: 'Financials',
      price: 42,
      volume: 60000,
      last_updated: new Date().toISOString(),
      day_change: 0.1,
      '52_Week_High': 45,
      '52_Week_Low': 35,
      EPS: 2.15,
      P_E_Ratio: 14,
      Dividend_Yield: 1.8,
      Market_Cap: 370000000,
      Beta: 1.1,
    },
  ]);
};

export default seed;
