const seed = async function (knex) {
  await knex(process.env.DB_NAME).del();
  await knex(process.env.DB_NAME).insert([
    {
      symbol: 'AAPL',
      company_name: 'Apple Inc.',
      sector: 'Technology',
      price: 150,
      volume: 100000,
      last_updated: new Date().toISOString(),
      day_change: 0.5,
      fifty_two_week_high: 200,
      fifty_two_week_low: 100,
      eps: 3.15,
      p_e_ratio: 30,
      dividend_yield: 0.6,
      market_cap: 2000000000,
      beta: 1.2,
    },
    {
      symbol: 'MSFT',
      company_name: 'Microsoft Corporation',
      sector: 'Technology',
      price: 300,
      volume: 80000,
      last_updated: new Date().toISOString(),
      day_change: -1.2,
      fifty_two_week_high: 350,
      fifty_two_week_low: 250,
      eps: 5.75,
      p_e_ratio: 33,
      dividend_yield: 0.8,
      market_cap: 2000000000,
      beta: 1.1,
    },
    {
      symbol: 'GOOGL',
      company_name: 'Alphabet Inc.',
      sector: 'Technology',
      price: 2800,
      volume: 50000,
      last_updated: new Date().toISOString(),
      day_change: 1.8,
      fifty_two_week_high: 3000,
      fifty_two_week_low: 2400,
      eps: 50.25,
      p_e_ratio: 30.5,
      dividend_yield: 0.5,
      market_cap: 1800000000,
      beta: 1,
    },
    {
      symbol: 'BA',
      company_name: 'Boeing Co.',
      sector: 'Industrials',
      price: 243.78,
      volume: 95123,
      last_updated: new Date().toISOString(),
      day_change: -0.43,
      fifty_two_week_high: 278.57,
      fifty_two_week_low: 174.35,
      eps: 5.36,
      p_e_ratio: 24.7,
      dividend_yield: 1.2,
      market_cap: 145200000,
      beta: 1.3,
    },
    {
      symbol: 'AMZN',
      company_name: 'Amazon.com Inc.',
      sector: 'Consumer Discretionary',
      price: 3300,
      volume: 41000,
      last_updated: new Date().toISOString(),
      day_change: -12,
      fifty_two_week_high: 3550,
      fifty_two_week_low: 2900,
      eps: 52.3,
      p_e_ratio: 63.1,
      dividend_yield: 0,
      market_cap: 1650000000,
      beta: 1.1,
    },
    {
      symbol: 'NFLX',
      company_name: 'Netflix, Inc.',
      sector: 'Communication Services',
      price: 550,
      volume: 34000,
      last_updated: new Date().toISOString(),
      day_change: 2.5,
      fifty_two_week_high: 600,
      fifty_two_week_low: 480,
      eps: 4.13,
      p_e_ratio: 40,
      dividend_yield: 0,
      market_cap: 240000000,
      beta: 0.9,
    },
    {
      symbol: 'TSLA',
      company_name: 'Tesla, Inc.',
      sector: 'Consumer Discretionary',
      price: 700,
      volume: 56000,
      last_updated: new Date().toISOString(),
      day_change: 4.7,
      fifty_two_week_high: 900,
      fifty_two_week_low: 500,
      eps: 1.24,
      p_e_ratio: 80,
      dividend_yield: 0,
      market_cap: 800000000,
      beta: 2,
    },
    {
      symbol: 'JPM',
      company_name: 'JPMorgan Chase & Co.',
      sector: 'Financials',
      price: 150,
      volume: 32000,
      last_updated: new Date().toISOString(),
      day_change: 0.4,
      fifty_two_week_high: 170,
      fifty_two_week_low: 130,
      eps: 8.95,
      p_e_ratio: 12,
      dividend_yield: 1.6,
      market_cap: 470000000,
      beta: 1.2,
    },
    {
      symbol: 'NVDA',
      company_name: 'NVIDIA Corporation',
      sector: 'Technology',
      price: 220,
      volume: 29000,
      last_updated: new Date().toISOString(),
      day_change: 0.8,
      fifty_two_week_high: 250,
      fifty_two_week_low: 180,
      eps: 6.45,
      p_e_ratio: 28,
      dividend_yield: 0.3,
      market_cap: 550000000,
      beta: 1.3,
    },
    {
      symbol: 'BAC',
      company_name: 'Bank of America Corp',
      sector: 'Financials',
      price: 42,
      volume: 60000,
      last_updated: new Date().toISOString(),
      day_change: 0.1,
      fifty_two_week_high: 45,
      fifty_two_week_low: 35,
      eps: 2.15,
      p_e_ratio: 14,
      dividend_yield: 1.8,
      market_cap: 370000000,
      beta: 1.1,
    },
  ]);
};

export default seed;
